version: "3"
services:

  elasticsearch:
    image: elasticsearch:7.17.19
    # give the container a name
    # this will also set the container's hostname as elasticsearch
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      # limits elasticsearch to 1 GB of RAM
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      # The password for the 'elastic' user
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.http.ssl.enabled=false
      - network.host=0.0.0.0
    networks:
      - elastic

  kibana:
    image: kibana:7.17.19
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      # remember the container_name for elasticsearch?
      # we use it here to access that container
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      # Change this to true if you want to sent
      # telemetry data to kibana developers
      - TELEMETRY_ENABLED=false
    networks:
      - elastic

  logstash:
    image: logstash:7.17.19
    container_name: logstash
    ports:
      - 5044:5044
      - 5001:5001
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      ES_JAVA_OPTS: -Xmx2048m -Xms2048m"
      http.host: 0.0.0.0
      xpack.monitoring.enabled: 'false'
      xpack.monitoring.elasticsearch.url: http://elasticsearch:9200
    networks: 
      - elastic
    depends_on:
      - elasticsearch

networks:
  elastic:
    driver: bridge